version: 29.5.2

services: 
  organizador-financeiro:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=organizador-financeiro